### ISSUE TITLE
Doesn't work with TeXLive 2010 under Windows7

### ISSUE THREAD

**Issue by blumu** [blumu/latexdaemon#22]
_From [tkew...@gmail.com](https://code.google.com/u/106912413350811998319/) on February 11, 2011 19:14:26_

What steps will reproduce the problem? 1. Install TeXLive 2010 in default directory
2. Create any sample texfile in any directory
3. try to use latexdaemon What is the expected output? What do you see instead? \documentclass{article}
\begin{document}
Exemple
\end{document}

I expect it to work, but the output is:
[...]
  This is pdfTeX, Version 3.1415926-1.40.11 (Web2C 2010)
   restricted \write18 enabled.
   Source specials enabled.
  format name test-latex not written in fmtutil.cnf.
  Running the command C:\texlive\2010\bin\win32\fmtutil.exe
  Sorry, I can't find the format `test-latex.fmt'; will try`pdftex.fmt'.
  entering extended mode
  (./test.tex
  ! Undefined control sequence.
  l.1 \documentclass
                    {article}
  ! Undefined control sequence.
  l.2 \begin
            {document}
  [1{c:/texlive/2010/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] )
  (see the transcript file for additional information)<c:/texlive/2010/texmf-dis
t
  /fonts/type1/public/amsfonts/cm/cmr10.pfb>
  Output written on test.pdf (1 page, 13403 bytes).
  Transcript written on test.log.
  pdftex: unrecognized option `-aux-directory=TeXAux'

  kpathsea: Running mktexfmt test-latex.fmt

  The command name is C:\texlive\2010\bin\win32\mktexfmt
[...]

Every command seems to raise an Undefined Control Sequence error. I know you only tested it with MikTex, but is it known how to fix this with TexLive? What version of the product are you using? On what operating system? TeXLive 2010, Windows7 Professional Please provide any additional information below.

_Original issue: http://code.google.com/p/latexdaemon/issues/detail?id=23_

**Comment by blumu** [comment]
Fixed in #27 Released in LatexDaemon 0.11.47

**Comment by vedgar** [comment]
Sorry, it still doesn't work. Under TeXLive 2018 and Windows 10, I get the same problem.
